### PR TITLE
bump deps to langchain 0.3.1

### PR DESCRIPTION
**Pull request by motobob**
part one of https://github.com/crewAIInc/crewAI/issues/1352

### CODE REVIEW

**Comment by motobob** [comment]
test locally error for me even on main so please before merging please verify on your end. Thank you

**Comment by rohanarora** [comment]
Hi Evgeny (@motobob), You may want to take a quick look here at the test files which needed an update.
https://github.com/crewAIInc/crewAI-tools/compare/main...rohanarora:crewAI-tools:test_fixes

Please ignore the version bump-related commits.

**Comment by joaomdmoura** [comment]
We are also in the process of replacing poetry with UV what will making updating certain depenceis that ahve conflicts a little easier :D

**Comment by timschott** [comment]
@joaomdmoura hello! do you have an update on this? would love to use the new Flow feature but the newest crew version still points to 0.2.x for langchain

**Pull request closed without merging**
